language: cpp

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository --yes ppa:kalakris/cmake; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install cmake; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libglfw-dev; fi

script:
- mkdir build
- cd build
- cmake ..
- make -j2
